#!/usr/bin/env python3
"""
rsa_reminders.py — RSA scheduling reminders, generated by the RSA Agent (Python),
replacing the old external "RSAAlert" Google-Apps-Script reminder.

Scans the RSA Tracker for carts whose RSA hasn't been updated in more than
RSA_STALE_DAYS days and that still need RSA (not Completed RSA / not overall Passed),
groups them by store, and posts one Slack reminder per store. RSA ONLY — W&M is out of
scope, so no W&M reminders are produced.

    python3 rsa_reminders.py            # print the reminders (dry run — no Slack post)
    python3 rsa_reminders.py --post     # post to Slack via the configured webhook/bot

Or import and call post_rsa_reminders(notify) from the bot (a daily poller is started
by rsa_agent). The staleness bar is RSA_STALE_DAYS (default 13; matches the update bar).
"""
import os
import json
import time
import logging
import threading
from datetime import datetime

try:
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    pass

import rsa_sheets as sheets

log = logging.getLogger("rsa-agent.reminders")

STALE_DAYS      = float(os.environ.get("RSA_STALE_DAYS", "13"))       # "no update > N days"
# Fixed daily send time (local), like the old RSAAlert schedule — default 09:00.
REMINDER_HOUR   = int(os.environ.get("RSA_REMINDER_HOUR", "9"))
REMINDER_MINUTE = int(os.environ.get("RSA_REMINDER_MINUTE", "0"))
STATE_FILE      = os.environ.get("RSA_REMINDER_STATE_FILE", "rsa_reminder_state.json")
RSA_MENTION     = os.environ.get("RSA_REMINDER_MENTION", "")          # e.g. <@U07..> to @-tag an owner

# RSA states that still need scheduling/attention (i.e. NOT done). A cart is reminded
# only when it's stale AND in one of these states (or blank).
_DONE_RSA   = {"completed rsa"}
_DONE_OVER  = {"passed"}


def find_stale_rsa(rows=None, min_days=STALE_DAYS):
    """Group stale, still-open RSA carts by store. Returns
    [{store, state, vendor, maxDays, carts:[{cartId, days, lastUpdated, vendor}]}]
    sorted by the store's longest-stale cart first."""
    rows = rows if rows is not None else sheets._rsa_data()
    by_store = {}
    for r in rows:
        cid = sheets._cell(r, sheets.C_CARTID)
        if not cid:
            continue
        rsa_status = sheets._cell(r, sheets.C_RSASTATUS)
        overall    = sheets._cell(r, sheets.C_OVERALL)
        if rsa_status.strip().lower() in _DONE_RSA or overall.strip().lower() in _DONE_OVER:
            continue                                   # RSA already done → no reminder
        days = sheets._days_stale(r)
        if not (isinstance(days, (int, float)) and days > min_days):
            continue                                   # fresh enough (or unknown) → skip
        store = sheets._cell(r, sheets.C_STORE) or "(unknown store)"
        g = by_store.setdefault(store, {"store": store, "state": sheets._cell(r, sheets.C_STATE),
                                        "vendor": None, "maxDays": 0, "carts": []})
        g["carts"].append({"cartId": cid, "days": days,
                           "lastUpdated": sheets._cell(r, sheets.C_LASTUPD) or "Not recorded",
                           "vendor": sheets._cell(r, sheets.C_RSAVENDOR)})
        g["maxDays"] = max(g["maxDays"], days)
    # one vendor per store when they all agree (so we can say "schedule with X")
    for g in by_store.values():
        vendors = {c["vendor"] for c in g["carts"] if c["vendor"]}
        g["vendor"] = next(iter(vendors)) if len(vendors) == 1 else None
        g["carts"].sort(key=lambda c: -c["days"])
    return sorted(by_store.values(), key=lambda g: -g["maxDays"])


def format_reminder(group, mention=RSA_MENTION):
    """One store's RSA scheduling reminder (RSA only — no W&M)."""
    n = len(group["carts"])
    who = (f" with *{group['vendor']}*" if group["vendor"] else "")
    head = (f":calendar: *RSA Scheduling Reminder*{(' ' + mention) if mention else ''} — "
            f"{group['store']} — {n} cart{'s' if n != 1 else ''} with no RSA update "
            f"(longest: {int(group['maxDays'])} days):")
    lines = [f"• `{c['cartId']}` — {int(c['days'])} days without RSA update "
             f"(last updated: {c['lastUpdated']})" for c in group["carts"]]
    tail = f"Please schedule{who} and update the tracker. <{sheets.webapp_url()}|Open in webapp>"
    return head + "\n" + "\n".join(lines) + "\n" + tail


def post_rsa_reminders(notify=None, min_days=STALE_DAYS, mention=RSA_MENTION):
    """Find stale RSA carts and post one reminder per store. notify(text) posts to Slack;
    if None, the reminders are logged (dry run). Returns a small summary dict."""
    try:
        groups = find_stale_rsa(min_days=min_days)
    except Exception as e:
        log.warning("rsa_reminders: could not read the tracker: %s", e)
        return {"error": str(e)}
    for g in groups:
        msg = format_reminder(g, mention)
        if notify:
            try:
                notify(msg)
            except Exception:
                log.exception("rsa_reminders: notify failed")
        else:
            log.info(msg)
    return {"stores": len(groups), "carts": sum(len(g["carts"]) for g in groups), "minDays": min_days}


def _last_posted_date():
    try:
        with open(STATE_FILE) as f:
            return json.load(f).get("lastPosted")
    except Exception:
        return None


def _mark_posted(date_str):
    try:
        tmp = STATE_FILE + ".tmp"
        with open(tmp, "w") as f:
            json.dump({"lastPosted": date_str}, f)
        os.replace(tmp, STATE_FILE)
    except Exception as e:
        log.warning("could not save %s: %s", STATE_FILE, e)


def start_poller(notify=None, hour=REMINDER_HOUR, minute=REMINDER_MINUTE):
    """Run the RSA reminders on a FIXED daily schedule (like the old RSAAlert), in a
    daemon thread started by rsa_agent. Posts once per day at/after HH:MM local time and
    records the date, so restarts don't re-post and the process running longer than a day
    keeps firing every day. Set RSA_REMINDER_HOUR/MINUTE to change the time."""
    def loop():
        log.info("RSA reminder poster scheduled daily at %02d:%02d (stale > %s days)",
                 hour, minute, STALE_DAYS)
        while True:
            try:
                now = datetime.now()
                today = now.strftime("%Y-%m-%d")
                due = (now.hour, now.minute) >= (hour, minute)
                if due and _last_posted_date() != today:
                    post_rsa_reminders(notify=notify)
                    _mark_posted(today)      # once per day, even across restarts
            except Exception as e:
                log.error("rsa_reminders loop error: %s", e)
            time.sleep(300)                  # re-check every 5 min
    t = threading.Thread(target=loop, name="rsa-reminders", daemon=True)
    t.start()
    return t


def main():
    import argparse
    ap = argparse.ArgumentParser(description="Post RSA scheduling reminders (RSA only; W&M out of scope).")
    ap.add_argument("--post", action="store_true", help="post to Slack (default just prints)")
    ap.add_argument("--min-days", type=float, default=STALE_DAYS, help=f"staleness bar (default {STALE_DAYS:g})")
    args = ap.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    if args.post:
        # Lazy import so a dry run needs no Slack config.
        try:
            from rsa_agent import slack
            chan = os.environ.get("RSA_MONITOR_CHANNEL", "C0ARJQWG7RP")
            notify = (lambda m: slack.client.chat_postMessage(channel=chan, text=m)) if chan else None
        except Exception:
            notify = None
        res = post_rsa_reminders(notify=notify, min_days=args.min_days)
    else:
        for g in find_stale_rsa(min_days=args.min_days):
            print(format_reminder(g) + "\n")
        res = {"stores": "(dry run)"}
    print("rsa_reminders:", res)


if __name__ == "__main__":
    main()
